### ISSUE TITLE
Not working on Windows 10 

### ISSUE THREAD

**Issue by bhaskarkannan** [vah13/extractTVpasswords#3]
We tried this script(python) on windows 10 and Team viewer 12.0.7xxx. But we could not get the expected result.

**Comment by vah13** [comment]
which kind of error do you get?

**Comment by bhaskarkannan** [comment]
Script running . But I dont get  username and password of the target(Tv)

**Comment by lance0** [comment]
post the shell. what version of python are you running?

**Comment by bhaskarkannan** [comment]
we are using python 2.7

**Comment by vah13** [comment]
so, I tested on Windows 8.1 and well worked,
I will try to setup Windows 10 and test it

**Comment by bhaskarkannan** [comment]
Sure test it and let me know the result...Thank you

**Comment by vah13** [comment]
can you dump the memory and search the password in the memory or using packer process to fast search the password?

**Comment by bhaskarkannan** [comment]
I have not done yet.. Will do and let you know..

**Comment by vah13** [comment]
well working on 
```
OS Name:                   Microsoft Windows Server 2016 Standard Evaluation
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
```
try to compile and execute cpp file.
