### ISSUE TITLE
Debug Assertion Failed

### ISSUE THREAD

**Issue by um3ha4a** [vah13/extractTVpasswords#7]
![default](https://user-images.githubusercontent.com/33953467/42981312-1c39e57c-8c0e-11e8-8b73-e90543f22423.png)
![default](https://user-images.githubusercontent.com/33953467/42981333-3389f3de-8c0e-11e8-9082-57a854113705.png)
Hi,I use IP address instead of ID to connect and I got this error message, anyidea what caused it?

**Comment by vah13** [comment]
hi, 
nope, I never tested IP instead of ID :-(
